name: Deploy app on two https servers


on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        http-server:
          - ssh_host: ${{ secrets.FIRST_HOST }}
            ssh_user: ${{ secrets.FIRST_USER }}

          - ssh_host: ${{ secrets.SECOND_HOST }}
            ssh_user: ${{ secrets.SECOND_USER }}

    name: Deploy new docker image on both http servers
    runs-on: self-hosted 
