services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .compose-env

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysqlvolume:/var/lib/mysql
    env_file:
      - .compose-env

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mysqlvolume:
