name: Deploy app on two web servers


on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        web-server: ["${{ vars.FIRST_HOST }}", "${{ vars.SECOND_HOST }}"]

    name: Deploy new docker image on both web servers
    runs-on: self-hosted 
    steps:
      - name: Deploy ${{ matrix.web-server }}
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run:  |
          echo $SSH_KEY > ~/.ssh/gh_actions
          chmod 600 ~/.ssh/gh_actions
          ssh -i ~/.ssh/gh_actions root@${{ matrix.web-server }} "cd /capstone-project && git pull && docker compose up -d web"
