name: Test and build docker image

on:
  push:
  pull_request:
    branches:
      - main

jobs: test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run:  pip install -r requirements.txt

      - name: Run Test
        run: python test_app.py

  build_and_push:
    if: ${{ github.event_name == 'push' }}
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to hub.docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            msa3dfa/capstone-app:latest
            msa3daf/capstone-app:${{ github.sha }}

